name: myenv
dependencies:
  - python=3.12.4
  - pip
  - pip:
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - mlflow
    - imbalanced-learn
    - jupyter
    - xgboost
    - ucimlrepo
    - pylint
    - pydantic
    - Flask
    - tqdm